module.exports = [
	{ title: "Typography", html: require('./components/typography/typography.jsx') },
	{ title: "Color Palette", html: require('./components/variables/colors.jsx') },
	{ title: "Icons & Labels", html: require('./components/icons/icons.jsx') },
	{ title: "Buttons & Links",			html: require('./components/forms/buttons.jsx') },
	{ title: "Checkboxes & Radios",	html: require('./components/forms/checkbox-radio.jsx') },
	{ title: "Inputs",			html: require('./components/forms/input.jsx') },
	{ title: "Slats",				html: require('./components/slats/slats.jsx') },
	{ title: "Tables",				html: require('./components/tables/tables.jsx') },
	{ title: "Cards",	html: require('./components/cards/cards.jsx') },
	{ title: "Navigation",	html: require('./components/navigation/navigation.jsx') },
	{ title: "Textarea",		html: require('./components/forms/textarea.jsx') },
	{ title: "Pickers",		html: require('./components/pickers/pickers.jsx') },
	{ title: "Toasters & Banners",		html: require('./components/banners/banners.jsx') },
	{ title: "Menus",		html: require('./components/menus/menus.jsx') },
	{ title: "Modals",		html: require('./components/modals/modals.jsx') },
	{ title: "Lists",		html: require('./components/lists/lists.jsx') },
	{ title: "Loaders",		html: require('./components/loaders/loaders.jsx') },
	{ title: "JavaScript Widgets", html: require('./js-widgets.jsx')}
];
